"""
СИСТЕМА АВТОМАТИЧЕСКОГО ПЕРЕНОСА СОСТОЯНИЯ ПРОЕКТА
"""
from datetime import datetime
import json
import pandas as pd
from pathlib import Path
from .paths import REPORTS_DIR


class ProjectStateTransfer:
    def __init__(self):
        self.transfer_dir = REPORTS_DIR / 'transfer'
        self.transfer_dir.mkdir(exist_ok=True)

        self.auto_report_path = self.transfer_dir / 'AUTO_REPORT.md'
        self.state_file = self.transfer_dir / 'project_state.json'

    def generate_auto_report(self, latest_results: dict = None, current_experiment: str = ""):
        """Генерация автоматического отчета"""

        report = f"""
# 🤖 MOEX AI BOT - AUTOMATED TRANSFER REPORT
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 📊 ПОСЛЕДНИЕ РЕЗУЛЬТАТЫ БЭКТЕСТА
{self._format_results(latest_results)}

## 🔬 ТЕКУЩИЙ ЭКСПЕРИМЕНТ
{current_experiment}

## 🎯 ПРИОРИТЕТНЫЕ ЗАДАЧИ
{self._get_priority_tasks()}

## 📝 ИСТОРИЯ ЭКСПЕРИМЕНТОВ
{self._get_experiment_history()}

## 🐛 ИЗВЕСТНЫЕ ПРОБЛЕМЫ
{self._get_known_issues()}

## 💡 РЕКОМЕНДАЦИИ ДЛЯ ПРОДОЛЖЕНИЯ
{self._get_continuation_recommendations()}

---
*Auto-generated by transfer_system.py*
"""

        with open(self.auto_report_path, 'w', encoding='utf-8') as f:
            f.write(report)

        print(f"✅ Автоотчет обновлен: {self.auto_report_path}")

    def save_project_state(self, state_data: dict):
        """Сохранение состояния проекта"""
        state_data['last_updated'] = datetime.now().isoformat()
        state_data['token_usage_alert'] = "95_PERCENT"  # или "NORMAL"

        with open(self.state_file, 'w', encoding='utf-8') as f:
            json.dump(state_data, f, indent=2, ensure_ascii=False)

    def load_project_state(self) -> dict:
        """Загрузка состояния проекта"""
        if self.state_file.exists():
            with open(self.state_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        return {}

    def _format_results(self, results: dict) -> str:
        if not results:
            return "```json\n{}\n```"

        formatted = []
        for symbol, metrics in results.items():
            formatted.append(f"- **{symbol}**: {metrics.get('total_trades', 0)} сделок, "
                             f"WR: {metrics.get('win_rate', 0):.1%}, "
                             f"Return: {metrics.get('total_return', 0):.2%}")

        return "\n".join(formatted) if formatted else "Нет данных"

    def _get_priority_tasks(self):
        return """
1. **🚨 URGENT**: Починить генерацию сигналов (0 сделок)
2. **🔧 HIGH**: Внедрить диагностику данных и предсказаний  
3. **📈 MEDIUM**: Упростить режимную логику до VOLA+TREND ядра
4. **⚡ LOW**: Настроить частотные ограничители
"""

    def _get_experiment_history(self):
        return """
- 2025-11-11: Первая режимная стратегия - 0 сделок
- 2025-11-11: Понижены пороги в dynamic_regime_detector
- 2025-11-11: Добавлена диагностика данных
- 2025-11-11: Создана система переноса состояния
"""

    def _get_known_issues(self):
        return """
- ❌ regime_backtest показывает 0 сделок
- ⚠️ Возможные проблемы с выравниванием фич GB модели
- 🔍 Слишком агрессивные фильтры в стратегиях
"""

    def _get_continuation_recommendations(self):
        return """
- Начать с emergency_debug_strategy для получения первых сделок
- Постепенно добавлять сложность после стабилизации
- Использовать transfer_system для сохранения контекста
"""